#!/usr/bin/env python3
"""
Regenerate the 'Contributing to' section in README.md from live GitHub data.

Pulls all PRs authored by $AUTHOR via `gh search prs` (works with GITHUB_TOKEN
in Actions, or any authenticated `gh` session locally), groups by repo,
sorts by stargazer count, and rewrites everything between the marker comments:

  <!-- CONTRIBUTING-TO:START -->
  ...
  <!-- CONTRIBUTING-TO:END -->

Only the section between markers is replaced; the rest of README.md is untouched.

Usage:
  AUTHOR=sanjibani python3 scripts/update-contributions.py
  AUTHOR=sanjibani python3 scripts/update-contributions.py --dry-run   # print, don't write
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent  # repo root (sanjibani/)
README = REPO / "README.md"
START_MARKER = "<!-- CONTRIBUTING-TO:START -->"
END_MARKER = "<!-- CONTRIBUTING-TO:END -->"
AUTO_NOTE = (
    "<!-- Auto-generated by .github/workflows/update-contributions.yml "
    "— do not edit by hand. -->"
)


def run_json(cmd: list[str]) -> list[dict]:
    r = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return json.loads(r.stdout)


def fetch_prs(author: str) -> list[dict]:
    """Return list of {repo, number, title, state, merged} for the author."""
    prs: list[dict] = []
    # Open PRs — always show
    for p in run_json(
        [
            "gh", "search", "prs",
            "--author", author,
            "--state", "open",
            "--limit", "100",
            "--json", "repository,title,url,number,state",
        ]
    ):
        prs.append({
            "repo": p["repository"]["nameWithOwner"],
            "title": p["title"],
            "url": p["url"],
            "number": p["number"],
            "merged": False,
            "state": "open",
        })
    # Closed PRs — only the ones that landed (merged). We drop closed-not-merged
    # because those are usually retired PRs (wrong base branch, duplicate, etc.)
    closed = run_json(
        [
            "gh", "search", "prs",
            "--author", author,
            "--state", "closed",
            "--limit", "100",
            "--json", "repository,title,url,number,state",
        ]
    )
    if closed:
        merged_lookup = fetch_merged_set([p["url"] for p in closed])
        for p in closed:
            if p["url"] not in merged_lookup:
                continue  # skip closed-not-merged
            prs.append({
                "repo": p["repository"]["nameWithOwner"],
                "title": p["title"],
                "url": p["url"],
                "number": p["number"],
                "merged": True,
                "state": "merged",
            })
    return prs


def fetch_merged_set(pr_urls: list[str]) -> set[str]:
    """Return the subset of PR URLs that are merged, using GraphQL."""
    # GraphQL `search` API has mergedAt field for PRs
    query = """
    query($q: String!) {
      search(query: $q, type: ISSUE, first: 100) {
        nodes { ... on PullRequest { url mergedAt } }
      }
    }
    """
    q = "author:sanjibani is:pr is:merged"
    r = subprocess.run(
        ["gh", "api", "graphql",
         "-f", f"query={query}",
         "-f", f"q={q}"],
        capture_output=True, text=True, check=True,
    )
    data = json.loads(r.stdout)
    return {
        node["url"]
        for node in data["data"]["search"]["nodes"]
        if node.get("mergedAt")
    }


def fetch_stars(repos: list[str]) -> dict[str, int]:
    """Return {repo: stargazers_count} for each 'owner/name' in repos."""
    stars: dict[str, int] = {}
    for repo in repos:
        r = subprocess.run(
            ["gh", "api", f"repos/{repo}", "--jq", ".stargazers_count"],
            capture_output=True, text=True, check=True,
        )
        try:
            stars[repo] = int(r.stdout.strip())
        except ValueError:
            stars[repo] = 0
    return stars


def star_badge(repo: str) -> str:
    return (
        f"[![GitHub stars](https://img.shields.io/github/stars/{repo}"
        f"?style=flat&color=gold)](https://github.com/{repo})"
    )


def short_title(t: str) -> str:
    """Strip a noisy prefix and tidy the title for display."""
    # 'docs: fix broken links ...' -> 'fix broken links ...'
    t = re.sub(r"^(docs|doc|fix|feat|chore|test|build|refactor|perf)\s*(\([^)]+\))?\s*:\s*",
               "", t, flags=re.IGNORECASE)
    return t.strip().rstrip(".")


def render_section(prs: list[dict], stars: dict[str, int]) -> str:
    """Build the markdown between the marker comments."""
    by_repo: dict[str, list[dict]] = defaultdict(list)
    for pr in prs:
        by_repo[pr["repo"]].append(pr)

    # sort repos by stars desc, then by name
    sorted_repos = sorted(by_repo.keys(), key=lambda r: (-stars.get(r, 0), r))

    out: list[str] = []
    out.append(
        "PRs to projects I depend on. Sorted by repo stars, descending. "
        "*(merged) = in upstream, (open) = in review.*"
    )
    out.append("")
    for repo in sorted_repos:
        # sort PRs within a repo: merged first, then by number desc
        repo_prs = sorted(
            by_repo[repo],
            key=lambda p: (not p["merged"], -p["number"]),
        )
        if all(p["merged"] for p in repo_prs):
            status = "**merged** ✅"
            pr_text = "; ".join(f"`{short_title(p['title'])}`" for p in repo_prs)
        elif all(not p["merged"] for p in repo_prs):
            status = "open"
            pr_text = "; ".join(f"`{short_title(p['title'])}`" for p in repo_prs)
        else:
            parts = []
            for p in repo_prs:
                st = "**merged** ✅" if p["merged"] else "open"
                parts.append(f"`{short_title(p['title'])}` ({st})")
            pr_text = "; ".join(parts)
        star_count = stars.get(repo, 0)
        out.append(
            f"- **[{repo}](https://github.com/{repo})** "
            f"{star_badge(repo)} ⭐{star_count:,} — {pr_text} ({status})"
        )
    return "\n".join(out)


def replace_section(readme_text: str, new_inner: str) -> str:
    """Replace the chunk between START_MARKER and END_MARKER (inclusive of markers)."""
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    new_chunk = f"{START_MARKER}\n{AUTO_NOTE}\n{new_inner}\n{END_MARKER}"
    new_text, n = pattern.subn(new_chunk, readme_text)
    if n != 1:
        print(f"ERROR: expected exactly 1 marker block, found {n}", file=sys.stderr)
        sys.exit(1)
    return new_text


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="print diff and exit")
    ap.add_argument("--author", default=os.environ.get("AUTHOR", "sanjibani"))
    args = ap.parse_args()

    prs = fetch_prs(args.author)
    repos = sorted({p["repo"] for p in prs})
    stars = fetch_stars(repos)
    new_inner = render_section(prs, stars)

    original = README.read_text()
    updated = replace_section(original, new_inner)

    if updated == original:
        print("No change. README is already up to date.")
        return

    if args.dry_run:
        print("=== NEW SECTION ===")
        print(new_inner)
        return

    README.write_text(updated)
    print(f"Updated {README} — {len(prs)} PRs across {len(repos)} repos.")


if __name__ == "__main__":
    main()
